// generated by tools/tablenames.py - offline table rva -> class name map
// sources: exact method-address index (rcl_docdata.h + classes_docs), 'Class::method' strings
#pragma once

#include <stdint.h>

namespace rcl {

struct SeedName {
    uint32_t vt;
    const char *name;
};

static const SeedName kSeedNames[] = {
    { 0xf783a8, "ProfileDsp" },
    { 0xf78bf0, "FrequencyDelayLineCPU_Async" },
    { 0xf82868, "time_internal" },
    { 0xf9ee10, "ChatStreamItem" },
    { 0xfa75a8, "StorePromoShopItem" },
    { 0xfa9d60, "BuyChallengeLivesPopup" },
    { 0xfad7f0, "CompetitivePassPopup" },
    { 0xfae0e8, "CompetitiveSeasonStartPopup" },
    { 0xfae818, "DemonsOneSideEventMenuPopup" },
    { 0xfaf5e8, "PurchaseSkinGroupOfferPopup" },
    { 0xfb3460, "DemonsContestRewardSelectionPopup" },
    { 0xfb4a58, "EnterAgePopup" },
    { 0xfb4ee8, "EsportTournamentsPopup" },
    { 0xfb6360, "NewRecordNotification" },
    { 0xfbcb90, "MoviePlayerPopup" },
    { 0xfbe210, "PlayerCountryPopup" },
    { 0xfc18c0, "PurchaseSkinGroupOfferHighlightPopupHandler" },
    { 0xfc1bb0, "PurchaseHeroLvlUpMaterialPopupHandler" },
    { 0xfc1f10, "ClaimRankRewardPopupHandler" },
    { 0xfccac8, "TeamJoinRequestPopup" },
    { 0xfcf980, "DemonsCodexPopup" },
    { 0xfd1a80, "ArchetypeItemsInfoPopup" },
    { 0xfd3618, "RecordsPopup" },
    { 0xfd5ee8, "SCIDManager" },
    { 0xfd5fc8, "GameSCIDManager" },
    { 0xfd6070, "GameSCIDManager" },
    { 0xfd7250, "HomeScreen" },
    { 0xfd72d0, "HomeScreen" },
    { 0xfd8a48, "AllianceQuestsTrack" },
    { 0xfdcf88, "QuestsPopup" },
    { 0xfe2468, "ChatOptionsPopup" },
    { 0xfe3f18, "ClubHubPopup" },
    { 0xfe6bd8, "LogicSkinAnimSequenceData" },
    { 0xfe6ec8, "SkinAnimSequencePopup" },
    { 0xfe9d00, "BattleMode" },
    { 0xfed3d8, "LogicClaimRankUpRewardCommand" },
    { 0xff5248, "LogicCharacterServer" },
    { 0xffd118, "BindGoogleServiceAccountMessage" },
    { 0x10012c8, "TencentAntiAddictionInstructionExecutedMessage" },
    { 0x10058e8, "NativeFont" },
    { 0x100b410, "LogicJSONInReflector" },
    { 0x10af918, "DSPTransceiver" },
};

static const uint32_t kSeedNameCount = 42;

}  // namespace rcl
